// Generated by .NET Reflector from C:\Enlist\AppDataCollection\packages\Microsoft.Diagnostics.Tracing.EventSource.Redist.1.0.24\lib\net35\Microsoft.Diagnostics.Tracing.EventSource.dll
namespace System
{
    using System.Text;
    
    [Serializable]
    internal class Tuple<T1, T2>
    {
        private readonly T1 m_Item1;
        private readonly T2 m_Item2;
        
        public Tuple(T1 item1, T2 item2)
        {
            this.m_Item1 = item1;
            this.m_Item2 = item2;
        }
        
        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("(");
            builder.Append(this.m_Item1);
            builder.Append(", ");
            builder.Append(this.m_Item2);
            builder.Append(")");
            return builder.ToString();
        }
        
        public T1 Item1
        {
            get
            {
                return this.m_Item1;
            }
        }
        
        public T2 Item2
        {
            get
            {
                return this.m_Item2;
            }
        }
        
        private int Size
        {
            get
            {
                return 2;
            }
        }
    }
}
