# escape=`

FROM microsoft/windowsservercore

# SQL Server 2012 LocalDB
COPY SqlLocalDB.msi .
RUN ["powershell", "Start-Process", "-FilePath msiexec -ArgumentList /q, /i, SqlLocalDB.msi, IACCEPTSQLLOCALDBLICENSETERMS=YES -Wait"]
RUN ["powershell", "C:\\'Program Files'\\'Microsoft SQL Server'\\110\\Tools\\Binn\\SqlLocalDB.exe", "create", "azure", "-s"]


# Azure Storage Emulator
ADD  https://go.microsoft.com/fwlink/?linkid=717179&clcid=0x409 MicrosoftAzureStorageEmulator.msi
RUN ["powershell","Start-Process", "-FilePath msiexec -ArgumentList /q, /i, MicrosoftAzureStorageEmulator.msi -Wait"]
RUN ["powershell","C:\\'Program Files (x86)'\\'Microsoft SDKs'\\Azure\\'Storage Emulator'\\AzureStorageEmulator.exe", "init", "/server", "'(localdb)\\azure'"]
RUN ["powershell","C:\\'Program Files (x86)'\\'Microsoft SDKs'\\Azure\\'Storage Emulator'\\AzureStorageEmulator.exe", "status"]

EXPOSE 10000 10001 10002

# Configure and launch
COPY start.ps1 .
CMD .\start.ps1