// <copyright file="AssemblyInfo.cs" company="Microsoft">
// Copyright © Microsoft. All Rights Reserved.
// </copyright>

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Microsoft.ApplicationInsights.Channel.PersistenceChannel")]
[assembly: AssemblyDescription("Application Insights SDK Persistence channel")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyProduct("Application Insights SDK Windows Persistence channel")]
[assembly: AssemblyCopyright("Copyright © Microsoft. All Rights Reserved.")]

[assembly: ComVisible(false)]
[assembly: InternalsVisibleTo("Microsoft.ApplicationInsights.PersistenceChannel.Net35.Tests, PublicKey=" + AssemblyInfo.PublicKey)]
[assembly: InternalsVisibleTo("Microsoft.ApplicationInsights.PersistenceChannel.Net40.Tests, PublicKey=" + AssemblyInfo.PublicKey)]
[assembly: InternalsVisibleTo("Microsoft.ApplicationInsights.PersistenceChannel.Net45.Tests, PublicKey=" + AssemblyInfo.PublicKey)]
[assembly: InternalsVisibleTo("Microsoft.ApplicationInsights.PersistenceChannel.Wrt81.Tests, PublicKey=" + AssemblyInfo.PublicKey)]
[assembly: InternalsVisibleTo("Microsoft.ApplicationInsights.PersistenceChannel.Wp80.Tests, PublicKey=" + AssemblyInfo.PublicKey)]

// Assembly dynamically generated by Moq in unit tests
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2, PublicKey=0024000004800000940000000602000000240000525341310004000001000100c547cac37abd99c8db225ef2f6c8a3602f3b3606cc9891605d02baa56104f4cfc0734aa39b93bf7852f7d9266654753cc297e7d2edfe0bac1cdcf9f717241550e0a7b191195b7667bb4f64bcb8e2121380fd1d9d46ad2d92d2d15605093924cceaf74c4861eff62abf69b9291ed0a340e113be11e6a7d3113e92484cf7045cc7")]

[assembly: InternalsVisibleTo("Microsoft.ApplicationInsights.TestFramework, PublicKey=" + AssemblyInfo.PublicKey)]