//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error configuring performance counters, performance data may be incomplete. Please check the configuration. {0}.
        /// </summary>
        internal static string event_CounterCheckConfigurationEvent {
            get {
                return ResourceManager.GetString("event_CounterCheckConfigurationEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to perform counter collection....
        /// </summary>
        internal static string event_CounterCollectionAttemptEvent {
            get {
                return ResourceManager.GetString("event_CounterCollectionAttemptEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters successfully collected. Counter count: {0}, collection time: {1}.
        /// </summary>
        internal static string event_CounterCollectionSuccessEvent {
            get {
                return ResourceManager.GetString("event_CounterCollectionSuccessEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance counter specified as {1} in ApplicationInsights.config was not parsed correctly. Please make sure that a proper name format is used. Expected formats are \category(instance)\counter or \category\counter. Technical details: {0}.
        /// </summary>
        internal static string event_CounterParsingFailedEvent {
            get {
                return ResourceManager.GetString("event_CounterParsingFailedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance counter {1} has failed the reading operation. Error message: {0}.
        /// </summary>
        internal static string event_CounterReadingFailedEvent {
            get {
                return ResourceManager.GetString("event_CounterReadingFailedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance counter {0} has been successfully registered with performance collector..
        /// </summary>
        internal static string event_CounterRegisteredEvent {
            get {
                return ResourceManager.GetString("event_CounterRegisteredEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance counter {1} has failed to register with performance collector. Please make sure it exists. Technical details: {0}.
        /// </summary>
        internal static string event_CounterRegistrationFailedEvent {
            get {
                return ResourceManager.GetString("event_CounterRegistrationFailedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value or no value has been specified for ReportAs when configuring custom performance counter collection. The value will be stripped of invalid characters. ReportAs may not contain any digits or special characters except the following ones: /, _, - or a dot. Until the configuration is fixed, counter {0} will be reported as {1}. The invalid value specified is {2}..
        /// </summary>
        internal static string event_CounterReportAsStrippedEvent {
            get {
                return ResourceManager.GetString("event_CounterReportAsStrippedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance counter infrastructure has been initialized..
        /// </summary>
        internal static string event_ModuleHasBeenInitializedEvent {
            get {
                return ResourceManager.GetString("event_ModuleHasBeenInitializedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance counter infrastructure is being initialized. {0}.
        /// </summary>
        internal static string event_ModuleIsBeingInitializedEvent {
            get {
                return ResourceManager.GetString("event_ModuleIsBeingInitializedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send a telemetry item for performance collector. Error text: {0}.
        /// </summary>
        internal static string event_TelemetrySendFailedEvent {
            get {
                return ResourceManager.GetString("event_TelemetrySendFailedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error in performance counter infrastructure: {0}.
        /// </summary>
        internal static string event_UnknownErrorEvent {
            get {
                return ResourceManager.GetString("event_UnknownErrorEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter {0}: {1}.
        /// </summary>
        internal static string PerformanceCounterCheckConfigurationEntry {
            get {
                return ResourceManager.GetString("PerformanceCounterCheckConfigurationEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform the first read for performance counter. Category: {0}, counter: {1}, instance {2}.
        /// </summary>
        internal static string PerformanceCounterFirstReadFailed {
            get {
                return ResourceManager.GetString("PerformanceCounterFirstReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform the first read for performance counter. Category: {0}, counter: {1}, instance {2}.
        /// </summary>
        internal static string WebAppPerformanceCounterFirstReadFailed {
            get {
                return ResourceManager.GetString("WebAppPerformanceCounterFirstReadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to perform a read for performance counter {0}.
        /// </summary>
        internal static string PerformanceCounterReadFailed {
            get {
                return ResourceManager.GetString("PerformanceCounterReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform a read for performance counter {0}.
        /// </summary>
        internal static string WebAppPerformanceCounterReadFailed {
            get {
                return ResourceManager.GetString("WebAppPerformanceCounterReadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to register performance counter. Category: {0}, counter: {1}, instance: {2}..
        /// </summary>
        internal static string PerformanceCounterRegistrationFailed {
            get {
                return ResourceManager.GetString("PerformanceCounterRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register performance counter. Category: {0}, counter: {1}, instance: {2}..
        /// </summary>
        internal static string WebAppPerformanceCounterRegistrationFailed {
            get {
                return ResourceManager.GetString("WebAppPerformanceCounterRegistrationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to register performance counter. Category: {0}, counter: {1}, instance: {2}..
        /// </summary>
        internal static string WebAppPerformanceCounterAccessFailed {
            get {
                return ResourceManager.GetString("WebAppPerformanceCounterAccessFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category name is required..
        /// </summary>
        internal static string PerformanceCounterTelemetryCategoryNameIsRequired {
            get {
                return ResourceManager.GetString("PerformanceCounterTelemetryCategoryNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter name is required..
        /// </summary>
        internal static string PerformanceCounterTelemetryCounterNameIsRequired {
            get {
                return ResourceManager.GetString("PerformanceCounterTelemetryCounterNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance counter {0}.
        /// </summary>
        internal static string UnicodePerformanceCounterName {
            get {
                return ResourceManager.GetString("UnicodePerformanceCounterName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid value for Environment.ProcessorsCount: {0}.
        /// </summary>
        internal static string StandardProcessorsCountReadFailed
        {
            get
            {
                return ResourceManager.GetString("StandardProcessorsCountReadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid value for NUMBER_OF_PROCESSORS: {0}.
        /// </summary>
        internal static string WebAppProcessorsCountReadFailed
        {
            get
            {
                return ResourceManager.GetString("WebAppProcessorsCountReadFailed", resourceCulture);
            }
        }
    }
}
