# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# .NET CLI: https://docs.microsoft.com/dotnet/core/tools/
# Description: The purpose of this workflow is to verify that every solution in the repo successfully compiles.

name: Sanity Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sanity-build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        solution: [
          ./Everything.sln,
          ./ProjectsForSigning.sln,
          ./LOGGING/Logging.sln,
          ./BASE/Microsoft.ApplicationInsights.sln,
          ./WEB/Src/Microsoft.ApplicationInsights.Web.sln]

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

    - name: Setup dotnet
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

    - name: Restore
      run: dotnet restore ${{ matrix.solution }}

    - name: Build
      run: dotnet build ${{ matrix.solution }}
